window.gcexports.globalLexicon = {
  "border" : { "tk": 1, "name": "BORDER", "cls": "function", "length": 2 , "arity": 2 },
  "rounded-none" : { "tk": 1, "cls": "string", "val": "rounded-none", "length": 0, "arity": 0 },
  "rounded-sm" : { "tk": 1, "cls": "string", "val": "rounded-sm", "length": 0, "arity": 0 },
  "rounded" : { "tk": 1, "cls": "string", "val": "rounded", "length": 0, "arity": 0 },
  "rounded-md" : { "tk": 1, "cls": "string", "val": "rounded-md", "length": 0, "arity": 0 },
  "rounded-lg" : { "tk": 1, "cls": "string", "val": "rounded-lg", "length": 0, "arity": 0 },
  "rounded-xl" : { "tk": 1, "cls": "string", "val": "rounded-xl", "length": 0, "arity": 0 },
  "rounded-xxl" : { "tk": 1, "cls": "string", "val": "rounded-2xl", "length": 0, "arity": 0 },
  "rounded-xxxl" : { "tk": 1, "cls": "string", "val": "rounded-3xl", "length": 0, "arity": 0 },
  "rounded-full" : { "tk": 1, "cls": "string", "val": "rounded-full", "length": 0, "arity": 0 },
  "slate" : { "tk": 1, "cls": "string", "val": "slate-600", "length": 0, "arity": 0 },
  "gray" : { "tk": 1, "cls": "string", "val": "gray-600", "length": 0, "arity": 0 },
  "zinc" : { "tk": 1, "cls": "string", "val": "zinc-600", "length": 0, "arity": 0 },
  "neutral" : { "tk": 1, "cls": "string", "val": "neutral-600", "length": 0, "arity": 0 },
  "stone" : { "tk": 1, "cls": "string", "val": "stone-600", "length": 0, "arity": 0 },
  "red" : { "tk": 1, "cls": "string", "val": "red-600", "length": 0, "arity": 0 },
  "orange" : { "tk": 1, "cls": "string", "val": "orange-600", "length": 0, "arity": 0 },
  "amber" : { "tk": 1, "cls": "string", "val": "amber-600", "length": 0, "arity": 0 },
  "yello" : { "tk": 1, "cls": "string", "val": "yellow-600", "length": 0, "arity": 0 },
  "lime" : { "tk": 1, "cls": "string", "val": "lime-600", "length": 0, "arity": 0 },
  "green" : { "tk": 1, "cls": "string", "val": "green-600", "length": 0, "arity": 0 },
  "emerald" : { "tk": 1, "cls": "string", "val": "emerald-600", "length": 0, "arity": 0 },
  "teal" : { "tk": 1, "cls": "string", "val": "teal-600", "length": 0, "arity": 0 },
  "cyan" : { "tk": 1, "cls": "string", "val": "cyan-600", "length": 0, "arity": 0 },
  "sky" : { "tk": 1, "cls": "string", "val": "sky-600", "length": 0, "arity": 0 },
  "blue" : { "tk": 1, "cls": "string", "val": "amber-600", "length": 0, "arity": 0 },
  "indigo" : { "tk": 1, "cls": "string", "val": "indigo-600", "length": 0, "arity": 0 },
  "violet" : { "tk": 1, "cls": "string", "val": "violet-600", "length": 0, "arity": 0 },
  "purple" : { "tk": 1, "cls": "string", "val": "purple-600", "length": 0, "arity": 0 },
  "fuchsia" : { "tk": 1, "cls": "string", "val": "fuchsia-600", "length": 0, "arity": 0 },
  "pink" : { "tk": 1, "cls": "string", "val": "pink-600", "length": 0, "arity": 0 },
  "rose" : { "tk": 1, "cls": "string", "val": "rose-600", "length": 0, "arity": 0 },
  "t" : { "tk": 1, "cls": "string", "val": "rose-600", "length": 0, "arity": 0 },
  "l" : { "tk": 1, "cls": "string", "val": "rose-600", "length": 0, "arity": 0 },
  "r" : { "tk": 1, "cls": "string", "val": "rose-600", "length": 0, "arity": 0 },
  "b" : { "tk": 1, "cls": "string", "val": "rose-600", "length": 0, "arity": 0 },

  "hello" : { "tk": 1, "name": "HELLO", "cls": "function", "length": 1 , "arity": 1 },
  "val" : { "tk": 1, "name": "VAL", "cls": "function", "length": 2 , "arity": 2 },
  "key" : { "tk": 1, "name": "KEY", "cls": "function", "length": 2 , "arity": 2 },
  "len" : { "tk": 1, "name": "LEN", "cls": "function", "length": 1 , "arity": 1 },
  "concat" : { "tk": 1, "name": "CONCAT", "cls": "function", "length": 1 , "arity": 1 },
  "add" : { "tk": 1, "name": "ADD", "cls": "function", "length": 2 , "arity": 2 },
  "mul" : { "tk": 1, "name": "MUL", "cls": "function", "length": 2 , "arity": 2 },
  "pow" : { "tk": 1, "name": "POW", "cls": "function", "length": 2 , "arity": 2 },
  "style" : { "tk": 1, "name": "STYLE", "cls": "function", "length": 2, "arity": 2 },
  "map" : { "tk": 1, "name": "MAP", "cls": "function", "length": 2, "arity": 2 },
  "apply" : { "tk": 1, "name": "APPLY", "cls": "function", "length": 2, "arity": 2 },
  "in" : { "tk": 1, "name": "IN", "cls": "function", "length": 0, "arity": 0 },
  "arg" : { "tk": 1, "name": "ARG", "cls": "function", "length": 1, "arity": 1 },
  "data" : { "tk": 1, "name": "DATA", "cls": "function", "length": 1, "arity": 1 },
  "button" : { "tk": 1, "name": "BUTTON", "cls": "function", "length": 1, "arity": 1 },
  "primary" : { "tk": 1, "name": "PRIMARY", "cls": "function", "length": 1, "arity": 1 },
  "option-a" : { "tk": 1, "name": "OPTION_A", "cls": "function", "length": 1, "arity": 1 },
  "option-b" : { "tk": 1, "name": "OPTION_B", "cls": "function", "length": 1, "arity": 1 },
  "option-c" : { "tk": 1, "name": "OPTION_C", "cls": "function", "length": 1, "arity": 1 },
  "uppercase" : { "tk": 1, "name": "UPPERCASE", "cls": "function", "length": 1, "arity": 1 },
  "lowercase" : { "tk": 1, "name": "LOWERCASE", "cls": "function", "length": 1, "arity": 1 },
  "capitalize" : { "tk": 1, "name": "CAPITALIZE", "cls": "function", "length": 1, "arity": 1 },
  "normal-case" : { "tk": 1, "name": "NORMAL_CASE", "cls": "function", "length": 1, "arity": 1 },
  "shadow" : { "tk": 1, "name": "SHADOW", "cls": "function", "length": 1, "arity": 1 },
  "h-gradient" : { "tk": 1, "name": "H_GRADIENT", "cls": "function", "length": 1, "arity": 1 },
  "v-gradient" : { "tk": 1, "name": "V_GRADIENT", "cls": "function", "length": 1, "arity": 1 },
  "raised-bottom" : { "tk": 1, "name": "RAISED_BOTTOM", "cls": "function", "length": 1, "arity": 1 },
  "raised-top" : { "tk": 1, "name": "RAISED_TOP", "cls": "function", "length": 1, "arity": 1 },
  "input" : { "tk": 1, "name": "INPUT", "cls": "function", "length": 1, "arity": 1 },
  "img" : { "tk": 1, "name": "IMG", "cls": "function", "length": 1, "arity": 1 },
  "svg" : { "tk": 1, "name": "SVG", "cls": "function", "length": 2, "arity": 2 },
  "path" : { "tk": 1, "name": "PATH", "cls": "function", "length": 2, "arity": 2 },
  "code" : { "tk": 1, "name": "CODE", "cls": "function", "length": 2, "arity": 2 },
  "a" : { "tk": 1, "name": "A", "cls": "function", "length": 2, "arity": 2 },
  "ol" : { "tk": 1, "name": "OL", "cls": "function", "length": 2, "arity": 2 },
  "ul" : { "tk": 1, "name": "UL", "cls": "function", "length": 2, "arity": 2 },
  "li" : { "tk": 1, "name": "LI", "cls": "function", "length": 2, "arity": 2 },
  "title" : { "tk": 1, "name": "TITLE", "cls": "function", "length": 2, "arity": 2 },
  "span" : { "tk": 1, "name": "SPAN", "cls": "function", "length": 2, "arity": 2 },
  "p" : { "tk": 1, "name": "P", "cls": "function", "length": 2, "arity": 2 },
  "h3" : { "tk": 1, "name": "H3", "cls": "function", "length": 1, "arity": 1 },
  "div" : { "tk": 1, "name": "DIV", "cls": "function", "length": 2, "arity": 2 }
}
